#!/usr/bin/env python3
"""Generate assembler/ISS-style golden files for matrix RTL testbenches.

The RTL tests are module-level tests, while the existing ISS is a file-based
program simulator. This bridge keeps the comparison deterministic:
  * instruction words are generated by assembler/assembler.py
  * expected architectural effects are generated by a compact reference model
    for every matrix instruction currently supported by rme_rtl/matrix_dispatch.sv
"""

from __future__ import annotations

from pathlib import Path
import sys

REPO_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO_ROOT))

from assembler.assembler import Assembler  # noqa: E402


GOLDEN_DIR = REPO_ROOT / "sim" / "golden"

EW_OPS = [
    ("madd", 0),
    ("msub", 1),
    ("mmul", 2),
    ("mmax", 4),
    ("mumax", 5),
    ("mmin", 6),
    ("mumin", 7),
    ("msrl", 8),
    ("msll", 9),
    ("msra", 10),
]

MAC_OPS = [
    ("mmaccu.w.b", True, True),
    ("mmaccus.w.b", True, False),
    ("mmaccsu.w.b", False, True),
    ("mmacc.w.b", False, False),
]


def u32(value: int) -> int:
    return value & 0xFFFFFFFF


def s32(value: int) -> int:
    value &= 0xFFFFFFFF
    return value - 0x100000000 if value & 0x80000000 else value


def u8(value: int) -> int:
    return value & 0xFF


def s8(value: int) -> int:
    value &= 0xFF
    return value - 0x100 if value & 0x80 else value


def pack_bytes(values: list[int]) -> int:
    word = 0
    for idx, value in enumerate(values[:4]):
        word |= (value & 0xFF) << (idx * 8)
    return u32(word)


def byte(word: int, idx: int) -> int:
    return (word >> (idx * 8)) & 0xFF


def write_words(path: Path, words: list[int]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("".join(f"{u32(word):08x}\n" for word in words), encoding="ascii")


def write_text(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")


def assemble_lines(lines: list[str]) -> list[int]:
    asm = Assembler()
    return [asm.assemble_line(line) for line in lines]


def ew_apply(func: int, a: int, b: int) -> int:
    a_u = u32(a)
    b_u = u32(b)
    a_s = s32(a)
    b_s = s32(b)
    shamt = a_u & 0x1F

    if func == 0:
        return u32(b_s + a_s)
    if func == 1:
        return u32(b_s - a_s)
    if func == 2:
        return u32(b_s * a_s)
    if func == 4:
        return u32(a_s if a_s > b_s else b_s)
    if func == 5:
        return u32(a_u if a_u > b_u else b_u)
    if func == 6:
        return u32(a_s if a_s < b_s else b_s)
    if func == 7:
        return u32(a_u if a_u < b_u else b_u)
    if func == 8:
        return u32(b_u >> shamt)
    if func == 9:
        return u32(b_u << shamt)
    if func == 10:
        return u32(s32(b_u) >> shamt)
    raise ValueError(f"unsupported EW func {func}")


def ew_inputs() -> tuple[list[int], list[int]]:
    src_a = [
        0x00000000, 0x00000001, 0xFFFFFFFF, 0x80000000,
        0x0000001F, 0x00000004, 0xFFFFFFFE, 0x7FFFFFFF,
        0x00000002, 0x00000003, 0x00000005, 0x00000008,
        0x00000010, 0x00000007, 0xFFFFFFF0, 0x0000000A,
    ]
    src_b = [
        0x00000011, 0xFFFFFFFE, 0x00000020, 0x7FFFFFFF,
        0x80000000, 0x00000030, 0xFFFFFFFD, 0x00000001,
        0x00000040, 0xFFFFFFF0, 0x00000003, 0x00000080,
        0x12345678, 0x87654321, 0x0000FFFF, 0xF0000000,
    ]
    return src_a, src_b


def ew_expected() -> list[int]:
    src_a, src_b = ew_inputs()
    out: list[int] = []

    for _, func in EW_OPS:
        for idx in range(16):
            out.append(ew_apply(func, src_a[idx], src_b[idx]))

    vector_row = 2
    for _, func in EW_OPS:
        for row in range(4):
            for beat in range(4):
                a = src_a[vector_row * 4 + beat]
                b = src_b[row * 4 + beat]
                out.append(ew_apply(func, a, b))

    return out


def misc_source_words() -> list[int]:
    return [u32(0x10000000 + row * 0x100 + beat) for row in range(4) for beat in range(4)]


def misc_expected() -> list[int]:
    src = misc_source_words()
    duplicated = [0x11223344] * 16
    moved = duplicated[:]

    after_mmovw_m_x = [0] * 16
    after_mmovw_m_x[6] = 0xA5A55A5A

    mmovw_x_m = [after_mmovw_m_x[6]]
    zeroed = [0] * 16

    row_slide = [0] * 16
    row_shift = 1
    for row in range(4):
        src_row = row + row_shift
        if src_row < 4:
            for beat in range(4):
                row_slide[row * 4 + beat] = src[src_row * 4 + beat]

    col_slide = [0] * 16
    col_shift = 2
    for row in range(4):
        for beat in range(4):
            src_beat = beat + col_shift
            if src_beat < 4:
                col_slide[row * 4 + beat] = src[row * 4 + src_beat]

    row_slide_up = [0] * 16
    row_up_shift = 1
    for row in range(4):
        if row >= row_up_shift:
            src_row = row - row_up_shift
            for beat in range(4):
                row_slide_up[row * 4 + beat] = src[src_row * 4 + beat]

    col_slide_up = [0] * 16
    col_up_shift = 2
    for row in range(4):
        for beat in range(4):
            if beat >= col_up_shift:
                src_beat = beat - col_up_shift
                col_slide_up[row * 4 + beat] = src[row * 4 + src_beat]

    return duplicated + moved + after_mmovw_m_x + mmovw_x_m + zeroed + row_slide + col_slide + row_slide_up + col_slide_up


def mac_inputs() -> tuple[list[list[int]], list[list[int]], list[list[int]]]:
    a = [
        [0x01, 0xFE, 0x7F, 0x80],
        [0x03, 0x04, 0xF0, 0x10],
        [0xFF, 0x02, 0x08, 0x81],
        [0x05, 0x06, 0x07, 0x08],
    ]
    b = [
        [0x02, 0x81, 0x03, 0x04],
        [0xFE, 0x05, 0x06, 0x80],
        [0x07, 0x08, 0xF0, 0x09],
        [0x0A, 0x0B, 0x0C, 0xFF],
    ]
    c_init = [
        [10, 20, 30, 40],
        [50, 60, 70, 80],
        [90, 100, 110, 120],
        [130, 140, 150, 160],
    ]
    return a, b, c_init


def mac_expected() -> list[int]:
    a, b, c_init = mac_inputs()
    out: list[int] = []
    for _, a_unsigned, b_unsigned in MAC_OPS:
        for row in range(4):
            for col in range(4):
                acc = c_init[row][col]
                for k in range(4):
                    av = u8(a[row][k]) if a_unsigned else s8(a[row][k])
                    bv = u8(b[k][col]) if b_unsigned else s8(b[k][col])
                    acc += av * bv
                out.append(u32(acc))
    return out


def ls_expected() -> tuple[list[int], list[int]]:
    a_load = [
        0x04030201, 0x08070605,
        0x14131211, 0x18171615,
    ]
    b_load = [
        0x24232221, 0x28272625,
        0x34333231, 0x38373635,
        0x44434241, 0x48474645,
    ]
    c_load = [
        0x00000101, 0x00000102, 0x00000103,
        0x00000201, 0x00000202, 0x00000203,
    ]

    dead = 0xDEADBEEF
    a_store = [
        a_load[0],
        (dead & 0xFFFFFF00) | byte(a_load[1], 0),
        a_load[2],
        (dead & 0xFFFFFF00) | byte(a_load[3], 0),
    ]
    b_store = [
        b_load[0],
        (dead & 0xFFFFFF00) | byte(b_load[1], 0),
        b_load[2],
        (dead & 0xFFFFFF00) | byte(b_load[3], 0),
        b_load[4],
        (dead & 0xFFFFFF00) | byte(b_load[5], 0),
    ]
    c_store = c_load[:]
    return a_load + b_load + c_load, a_store + b_store + c_store


def main() -> int:
    cases = {
        "config": [
            "mrelease",
            "msettilemi 2",
            "msettileni 3",
            "msettileki 5",
            "msettilem x0",
            "msettilen x0",
            "msettilek x0",
        ],
        "ew": [
            *[f"{name}.w.mm acc2, acc1, acc0" for name, _ in EW_OPS],
            *[f"{name}.w.mv.i acc2, acc1, acc0[2]" for name, _ in EW_OPS],
        ],
        "misc": [
            "mdupw.m.x tr2, x0",
            "mmov.mm tr3, tr2",
            "mmovw.m.x tr0, x5, x6",
            "mmovw.x.m x10, tr0, x5",
            "mzero acc0",
            "mrslidedown tr1, tr0, 1",
            "mcslidedown.w acc1, acc0, 2",
            "mrslideup tr2, tr0, 1",
            "mcslideup.w acc2, acc0, 2",
        ],
        "mac": [
            *[f"{name} acc{idx}, tr0, tr1" for idx, (name, _, _) in enumerate(MAC_OPS)],
        ],
        "ls": [
            "mlae8 tr0, (x0), x0",
            "msae8 tr0, (x0), x0",
            "mlbe8 tr1, (x0), x0",
            "msbe8 tr1, (x0), x0",
            "mlce32 acc0, (x0), x0",
            "msce32 acc0, (x0), x0",
        ],
    }

    asm_report: list[str] = []
    for name, lines in cases.items():
        words = assemble_lines(lines)
        write_words(GOLDEN_DIR / f"{name}_insn.mem", words)
        asm_report.append(f"[{name}]")
        asm_report.extend(f"{line:<36} 0x{word:08x}" for line, word in zip(lines, words))
        asm_report.append("")

    src_a, src_b = ew_inputs()
    write_words(GOLDEN_DIR / "ew_src_a.mem", src_a)
    write_words(GOLDEN_DIR / "ew_src_b.mem", src_b)
    write_words(GOLDEN_DIR / "ew_expected.mem", ew_expected())

    write_words(GOLDEN_DIR / "misc_source.mem", misc_source_words())
    write_words(GOLDEN_DIR / "misc_expected.mem", misc_expected())

    a, b, c_init = mac_inputs()
    write_words(GOLDEN_DIR / "mac_a_rows.mem", [pack_bytes(row) for row in a])
    write_words(GOLDEN_DIR / "mac_b_cols.mem", [pack_bytes([b[k][col] for k in range(4)]) for col in range(4)])
    write_words(GOLDEN_DIR / "mac_c_init.mem", [word for row in c_init for word in row])
    write_words(GOLDEN_DIR / "mac_expected.mem", mac_expected())

    ls_reg, ls_mem = ls_expected()
    write_words(GOLDEN_DIR / "ls_expected_reg.mem", ls_reg)
    write_words(GOLDEN_DIR / "ls_expected_mem.mem", ls_mem)

    write_text(
        GOLDEN_DIR / "generated_assembly.txt",
        "\n".join(asm_report)
        + "\n"
        + "Expected files are generated by tools/generate_matrix_iss_golden.py.\n",
    )
    print(f"Generated assembler/ISS golden files in {GOLDEN_DIR}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
